/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Compute */

#ifndef _Included_Compute
#define _Included_Compute
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Compute
 * Method:    compute
 * Signature: (IJ)D
 */
JNIEXPORT jdouble JNICALL Java_Compute_compute
  (JNIEnv *, jclass, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
